<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-7 m-auto p-3 mt-3">
				<div class="row">
					<div class="col-md-6 support-link-box">
						<div class="customer-support">
							<img alt="" src="assets/customer-service.png" class="img-fluid support-img" />

							<span class="font-13"><a href="#" class="support-link">Customer Support 1</a></span>
							<span class="font-13 split-line"><a href="#" class="support-link">Support 2</a></span>
						</div>
					</div>
					<div class="col-md-6 support-link-box">
						<div class="customer-support">
							<img alt="" src="assets/whatsapp.png" class="img-fluid whatsapp-img" />
							<span class="font-13"><a href="#" class="support-link">Customer Support 3</a></span>
							<span class="font-13 split-line"><a href="#" class="support-link">Support 4</a></span>
						</div>
					</div>
					<div class="col-md-12 extend-btn-box">
						<div class="extend-btn"></div>
					</div>
					<div class="col-md-4 support-link-box">
						<div class="customer-support">
							<i class="fa fa-skype font-24"></i>
							<span class="font-13"><a href="#" class="support-link">skyexchangeofficial</a></span>
						</div>
					</div>
					<div class="col-md-4 support-link-box">
						<div class="customer-support">
							<i class="fa fa-telegram font-24"></i>
							<span class="font-13"><a href="#" class="support-link">info@skyexchange.com</a></span>
						</div>
					</div>
					<div class="col-md-4 support-link-box">
						<div class="customer-support">
							<i class="fa fa-instagram font-24"></i>
							<span class="font-13"><a href="#" class="support-link">officialskyexchange</a></span>
						</div>
					</div>

					<div class="col-md-12 footer-content-box">
						<div class="powered-by">
							<div class="betfair-logo">
								<div class="font-10">Powered by</div>
								<img alt="" src="assets/betfair.png" class="betfair-logo" />
							</div>
							<div class="text-center font-14 px-4">License</div>
							<div class="footer-content">
								<p class="font-11 footer-content-text">
									Skyexch.art is operated by Sky Infotech N.V. a limited
									liability company incorporated under the laws of Curacao
									with company Registration number 152377 with registered
									office at Abraham de Veerstraat 9 , Curacao P.O Box 3421
									and is licensed and regulated by the Curacao authority
									as the regulatory body responsible holding a
									(Sub-license with License number 365/JAZ Sub-License
									GLH- OCCHKTW0707072017 granted on 6.07.2017). Players
									are requested not to contact any untrusted sources for
									https://www.skyexch.art/ accounts as this is an online
									site and they can only register independently without
									any agents. Only deposit through the account details
									generated by the system or provided by our official
									support team.
									<hr />
								<div class="contact-box">
									<div>

										<i class="fa fa-phone"></i>
										<span class="font-11 contact-details">+351926917651 / +351926917279</span>
									</div>

									<div>

										<i class="fa fa-envelope" aria-hidden="true"></i>
										<span class="font-11 contact-details">+351926917651 / +351926917279</span>
									</div>
								</div>
								</p>
							</div>
						</div>
					</div>

					<div class="col-md-12 mt-4">
						<div class="browser-wrap">
							<i class="fa fa-chrome mx-2 font-24 browser-icon" aria-hidden="true"></i>
							<i class="fa fa-firefox font-24 browser-icon" aria-hidden="true"></i>
						</div>
						<div class="font-11 w-100 text-center browser-wrap-text">
							Our website works best in the newest and last prior version of these browsers: <br>Google Chrome. Firefox
						</div>
					</div>
				</div>
			</div>
			<hr />
			<div class="col-md-8 m-auto">
				<ul class="footer-link-list">
					<li class="font-12 footer-links"><a href="#" id="policy-footer-link">Privacy Policy</a></li>
					<li class="font-12 footer-links"><a href="#" id="terms-footer-link">Terms and Conditions</a></li>
					<li class="font-12 footer-links"><a href="#" id="rules-footer-link">Rules and Regulations</a></li>
					<li class="font-12 footer-links"><a href="#" id="kyc-footer-link">KYC</a></li>
					<li class="font-12 footer-links"><a href="#" id="reponsible-footer-link">Responsible Gaming</a></li>
					<li class="font-12 footer-links"><a href="#" id="about-footer-link">About Us</a></li>
					<li class="font-12 footer-links"><a href="#" id="exclusion-footer-link">Self-exclusion Policy</a></li>
					<li class="font-12 footer-links"><a href="#" id="underage-footer-link">Underage Policy</a></li>
				</ul>
				<div class="w-100 d-flex justify-content-center">

					<img alt="" src="assets/ios.png" class="img-fluid ios-img" />
					<br />
				</div>
				<div>
					<p class="font-10 text-center">v1.11 - 2022-03-23 - 3.1MB</p>
				</div>
			</div>
		</div>
	</div>
</footer>


<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<!-- custom javascript -->
<script src="./js/script.js"></script>
</body>

</html>